In [1]:
import pandas as pd
import numpy as np
from nba_api.stats.endpoints import teamgamelogs
pd.set_option('display.max_columns', None)

In [2]:
team_game_logs = teamgamelogs.TeamGameLogs(
    season_nullable='2025-26',
    season_type_nullable= 'Playoffs',
    timeout= 60
)

In [3]:
playoff_game_logs = team_game_logs.get_data_frames()[0]
cavs_game_logs = playoff_game_logs[playoff_game_logs['TEAM_ABBREVIATION'] == 'CLE']
cavs_game_logs

,SEASON_YEAR,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,AVAILABLE_FLAG
5,2025-26,1610612739,CLE,Cleveland Cavaliers,0042500136,2026-05-01T00:00:00,CLE @ TOR,L,53.0,40,93,0.430,11,41,0.268,19,27,0.704,19,33,52,23,18.0,8,4,9,21,25,110,-2.0,1,47,47,47,1,27,6,60,47,11,70,40,29,73,3,35,7,42,75,30,57,84,30,13,37,49,1
16,2025-26,1610612739,CLE,Cleveland Cavaliers,0042500135,2026-04-29T00:00:00,CLE vs. TOR,W,48.0,43,81,0.531,18,36,0.500,21,28,0.750,4,31,35,20,15.0,8,8,8,16,21,125,5.0,1,1,1,1,5,14,65,10,4,32,3,23,21,53,89,48,78,66,54,30,10,73,3,49,7,39,1
36,2025-26,1610612739,CLE,Cleveland Cavaliers,0042500134,2026-04-26T00:00:00,CLE @ TOR,L,48.0,32,87,0.368,10,40,0.250,15,23,0.652,16,40,56,15,18.0,5,5,8,27,19,89,-4.0,1,47,47,47,5,79,31,84,60,16,78,72,49,80,10,4,3,88,75,71,42,73,85,74,86,51,1
59,2025-26,1610612739,CLE,Cleveland Cavaliers,0042500133,2026-04-23T00:00:00,CLE @ TOR,L,48.0,36,81,0.444,14,45,0.311,18,23,0.783,16,26,42,23,22.0,7,6,4,15,21,104,-22.0,1,47,47,47,5,62,65,48,15,7,57,47,49,40,10,75,50,42,87,41,27,25,1,49,56,87,1
70,2025-26,1610612739,CLE,Cleveland Cavaliers,0042500132,2026-04-20T00:00:00,CLE vs. TOR,W,48.0,44,83,0.530,13,40,0.325,14,22,0.636,8,27,35,22,14.0,13,5,3,20,24,115,10.0,1,1,1,1,5,8,53,11,26,16,50,74,66,81,62,72,78,50,47,7,42,16,20,23,19,29,1
84,2025-26,1610612739,CLE,Cleveland Cavaliers,0042500131,2026-04-18T00:00:00,CLE vs. TOR,W,48.0,44,81,0.543,16,32,0.500,22,28,0.786,7,26,33,24,17.0,9,0,4,28,23,126,13.0,1,1,1,1,5,8,65,7,7,54,3,19,21,37,73,75,85,32,68,24,91,25,88,30,4,18,1

In [31]:
playoff_game_logs['PTSA'] = playoff_game_logs['PTS'] - playoff_game_logs['PLUS_MINUS']
stats = ['PTS', 'PTSA', 'FG_PCT', 'FG3_PCT', 'FT_PCT', 'OREB',
         'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK',
         'PLUS_MINUS']


team_stats_df = (
    playoff_game_logs
    .groupby("TEAM_NAME")[stats]
    .mean().round(2)
    .reset_index()
)

In [32]:
team_stats_df

,TEAM_NAME,PTS,PTSA,FG_PCT,FG3_PCT,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,PLUS_MINUS
0,Atlanta Hawks,104.00,110.25,0.45,0.33,0.73,9.75,30.00,39.75,21.50,14.75,8.00,5.75,-6.25
1,Boston Celtics,114.00,99.50,0.46,0.38,0.80,13.00,34.25,47.25,26.00,13.25,5.25,5.75,14.50
2,Cleveland Cavaliers,108.50,109.25,0.47,0.35,0.71,11.75,29.75,41.50,21.00,17.75,8.50,4.00,-0.75
3,Denver Nuggets,105.50,112.25,0.40,0.28,0.83,7.75,34.25,42.00,22.00,10.75,6.00,2.75,-6.75
4,Detroit Pistons,101.33,102.67,0.43,0.30,0.73,11.00,35.00,46.00,21.67,17.67,8.00,9.67,-1.33
5,Houston Rockets,103.75,104.00,0.42,0.31,0.75,16.75,25.75,42.50,21.75,14.50,13.25,4.75,-0.25
6,Los Angeles Lakers,104.00,103.75,0.51,0.41,0.75,7.75,30.75,38.50,25.25,20.00,9.00,6.50,0.25
7,Minnesota Timberwolves,112.25,105.50,0.46,0.34,0.77,11.00,37.75,48.75,26.00,12.00,6.25,3.75,6.75
8,New York Knicks,110.25,104.00,0.46,0.39,0.79,11.50,33.75,45.25,21.50,14.50,7.75,4.25,6.25
9,Oklahoma City Thunder,120.00,100.00,0.47,0.33,0.87,13.00,32.67,45.67,25.00,8.67,11.00,6.33,20.00
10,Orlando Magic,102.67,101.33,0.41,0.33,0.75,12.67,32.33,45.00,21.67,15.00,11.67,6.67,1.33
11,Philadelphia 76ers,99.50,114.00,0.43,0.33,0.73,10.50,26.75,37.25,20.25,11.00,5.25,5.00,-14.50
12,Phoenix Suns,100.00,120.00,0.42,0.34,0.80,12.67,30.00,42.67,21.33,17.33,4.00,1.67,-20.00
13,Portland Trail Blazers,101.25,112.00,0.42,0.32,0.77,11.50,29.75,41.25,20.75,13.75,7.50,5.50,-10.75
14,San Antonio Spurs,112.00,101.25,0.47,0.41,0.79,11.50,33.50,45.00,24.00,14.75,9.25,7.00,10.75
15,Toronto Raptors,109.25,108.50,0.48,0.37,0.72,12.00,28.75,40.75,25.00,16.00,8.25,4.75,0.75

In [33]:
team_stats_df = team_stats_df.groupby('TEAM_NAME').agg({
    'PTS' : 'sum',
    'PTSA' : 'sum',
    'Possessions' : 'sum'
}).reset_index().rename(columns={
        "TEAM_NAME": "Team"})

team_stats_df['O_RTG'] = 100 * team_stats_df['PTS'] / team_stats_df['Possessions']
team_stats_df['D_RTG'] = 100 * team_stats_df['PTSA'] / team_stats_df['Possessions']
team_stats_df['NET_RTG'] = team_stats_df['O_RTG'] - team_stats_df['D_RTG']

KeyError: "Column(s) ['Possessions'] do not exist"

ModuleNotFoundError: No module named 'utils'

In [ ]:
playoff_game_logs['Possessions'] = 0.96*(((playoff_game_logs['FGA'])+(playoff_game_logs['TOV']))+0.44*(playoff_game_logs['FTA'])-playoff_game_logs['OREB'])
playoff_game_logs

In [ ]:
team_ratings

                 TEAM_NAME  PTS  Possessions
0            Atlanta Hawks  416     382.0032
1           Boston Celtics  456     369.9840
2      Cleveland Cavaliers  434     382.3104
3           Denver Nuggets  422     395.1744
4          Detroit Pistons  304     292.6464
5          Houston Rockets  300     286.5408
6       Los Angeles Lakers  320     278.2464
7   Minnesota Timberwolves  449     389.0304
8          New York Knicks  441     383.0400
9    Oklahoma City Thunder  360     280.6656
10           Orlando Magic  308     290.8416
11      Philadelphia 76ers  398     366.2976
12            Phoenix Suns  300     284.8512
13  Portland Trail Blazers  405     381.3888
14       San Antonio Spurs  448     381.5808
15         Toronto Raptors  437     385.8816